[package]
edition = "2021"
license = "GPLv3"
name = "app-promotion-rpc"
version = "0.1.0"

[dependencies]
codec = { workspace = true }
pallet-evm = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "sp-api/std", "sp-runtime/std", "sp-std/std"]
