[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'Unqiue pallet inflation'
edition = '2018'
homepage = 'https://substrate.io'
license = 'Unlicense'
name = 'pallet-inflation'
repository = 'https://github.com/usetech-llc/nft_private/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
serde = { version = "1.0.119" }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
pallet-balances = { default-features = false, version = '3.0.0' }
pallet-timestamp = { default-features = false, version = '3.0.0' }
pallet-randomness-collective-flip = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }
frame-benchmarking = { default-features = false, version = "3.0.0", optional = true }
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'codec/std',
    'serde/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-balances/std',
    'pallet-timestamp/std',
    'pallet-randomness-collective-flip/std',
    'sp-std/std',
    'sp-runtime/std',
    'frame-benchmarking/std',
]
runtime-benchmarks = ["frame-benchmarking"]
