[package]
authors = ["RMRK Team", "Unique Network <support@uniquenetwork.io>"]
description = "RMRK proxy data structs definitions"
edition = "2021"
homepage = "https://unique.network"
license = 'GPLv3'
name = "rmrk-traits"
repository = 'https://github.com/UniqueNetwork/unique-chain'
version = "0.1.0"

[dependencies]
# Note: `package = "parity-scale-codec"` must be supplied since the `Encode` macro searches for it.
codec = { workspace = true, package = "parity-scale-codec" }

scale-info = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = ["std"]
serde1 = ["serde/alloc"]
std = ["codec/std", "serde/std", "serde1"]
