[workspace]
resolver = "2"
members = [
    'node',
    'pallets/*',
    'primitives',
    'runtime',
    'crates/evm-coder',
    'crates/evm-coder-macros',
]
resolver = "2"
[profile.release]
panic = 'unwind'
