version: "3.5"

services:
  node_einstein:
    image: nft-parachain
    ports:
      - 9944:9944
      - 9935:9935
    build:
      context: ./
      dockerfile: Dockerfile-testnet
    volumes:
      - ./chain-data-einstein:/chain-data
    networks: 
      - substrate_network
    environment:
      - NODE=einstein
      - P2PPORT=30335
      - WSPORT=9944
      - RPCPORT=9935
      - BOOTNODE=True

  node_newton:
    image: nft-parachain
    ports:
      - 9946:9946
      - 9936:9936
    build:
      context: ./
      dockerfile: Dockerfile-testnet
    volumes:
      - ./chain-data-newton:/chain-data
    networks: 
      - substrate_network
    environment:
      - NODE=newton
      - P2PPORT=30336
      - WSPORT=9946
      - RPCPORT=9936
      - BOOTNODE=False
      - BOOTPORT=30335
      - BOOTID=12D3KooWRYNrSRQvJ73esUhpyETQNJWGfC2LQ9dW3HJtzHJM28Hc

networks: 
  substrate_network:
    driver: bridge
    name: substrate_network
