version: "3.5"

services:
  node_validator1:
    image: nft_node_test
    container_name: validator1_test
    ports:
      - 9944:9944
    build:
      context: ./
      dockerfile: Dockerfile
#    volumes:
#      - ./chain-data:/chain-data
    networks:
      - node_test_network
    command: bash -c "/usr/local/bin/nft --dev --tmp --ws-external --rpc-external"

  integration_tests:
    container_name: integration_test
    image: int_test
    build:
      context: ./
      dockerfile: Dockerfile-tests
      volumes:
      - ./tests/src/config_docker.ts:/nft_parachain/tests/src/config.ts
    networks:
      - node_test_network
    depends_on:
      - node_validator1

   unit_tests:
    container_name: unit_test
    image: nft_unit_test
    build:
      context: ./
      dockerfile: Dockerfile-unit
    container_name: unit_test
    networks:
      - node_test_network
   # command: bash -c 'while true; do sleep 20; df -h; done'
    command: bash -c 'cargo test'

networks:
  node_test_network:
    name: node_test_network
    driver: bridge