version: "3"

services:
  node:
    image: nft-parachain
    ports:
      - 9944:9944
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
     - chain-data:/chain-data/
    command: 
      cargo run -- --dev --ws-external --rpc-external --base-path=./chain-data
      
volumes:
    chain-data: