version: "3.5"

services:
  node_validator1:
    image: nft_node_test
    container_name: validator1_test
    ports:
      - 9944:9944
      - 9844:9844
      - 9933:9933
    build:
      context: ./
      dockerfile: Dockerfile-parachain
    volumes:
#      - ./chain-data:/chain-data
      - ./launch-config.json:/polkadot-launch/launch-config.json
      - ./runtime_types.json:/polkadot-launch/runtime_types.json
    environment:
      - WASM_TOOLCHAIN=${WASM_TOOLCHAIN}
      - POLKA_VERSION=${POLKA_VERSION}
      - NFT_BRANCH=${NFT_BRANCH}
    env_file:
      - ./.env-parachain
    networks:
      - node_test_network
    #command: bash -c "yarn --cwd polkadot-launch start"
    #command: bash -c 'while true; do sleep 60; df -h; done'

  integration_tests:
    container_name: integration_test
#    ports:
#      - 9944:9944
#      - 9844:9844
#      - 9933:9933
    image: int_test
    build:
      context: ./
      dockerfile: Dockerfile-tests
    volumes:
      - ./tests/src/config_docker.ts:/nft_parachain/tests/src/config.ts
      - ./mochawesome-report:/nft_parachain/tests/mochawesome-report
#    command: bash -c 'while true; do sleep 20; df -h; done'
    networks:
      - node_test_network
    depends_on:
      - node_validator1

#  unit_tests:
#    container_name: unit_test
#    image: nft_unit_test
#    build:
#      context: ./
#      dockerfile: Dockerfile-unit
#    container_name: unit_test
#    networks:
#      - node_test_network
   # command: bash -c 'while true; do sleep 20; df -h; done'
#    command: bash -c 'cargo test'

networks:
  node_test_network:
    name: node_test_network
    driver: bridge
