[package]
name = "pallet-refungible"
version = "0.1.0"
license = "GPLv3"
edition = "2021"

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.1.2'

[dependencies]
frame-support = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
frame-system = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-runtime = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-std = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-core = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "master" }
pallet-common = { default-features = false, path = '../common' }
up-data-structs = { default-features = false, path = '../../primitives/data-structs' }
frame-benchmarking = { default-features = false, optional = true, git = 'https://github.com/paritytech/substrate', branch = 'master' }
scale-info = { version = "2.0.1", default-features = false, features = [
    "derive",
] }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "up-data-structs/std",
    "pallet-common/std",
    'frame-benchmarking/std',
    "pallet-evm/std",
]
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
]
