[package]
edition = "2021"
license = "GPLv3"
name = "pallet-rmrk-equip"
version = "0.1.2"

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = "3.1.2" }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-common = { default-features = false, path = "../common" }
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/unique-frontier", branch = "unique-polkadot-v0.9.37" }
pallet-nonfungible = { default-features = false, path = "../../pallets/nonfungible" }
pallet-rmrk-core = { default-features = false, path = "../proxy-rmrk-core" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
up-data-structs = { default-features = false, path = "../../primitives/data-structs" }

[features]
default = ["std"]
runtime-benchmarks = ['frame-benchmarking', 'frame-support/runtime-benchmarks', 'frame-system/runtime-benchmarks']
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-common/std",
	"pallet-evm/std",
	"pallet-nonfungible/std",
	"pallet-rmrk-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"up-data-structs/std",
	'frame-benchmarking/std',
]
try-runtime = ["frame-support/try-runtime"]
