[package]
edition = "2021"
license = "GPLv3"
name = "pallet-rmrk-equip"
version = "0.1.2"

[dependencies]
# Note: `package = "parity-scale-codec"` must be supplied since the `Encode` macro searches for it.
codec = { workspace = true, package = "parity-scale-codec" }

scale-info = { workspace = true }

frame-benchmarking = {workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-common = { workspace = true }
pallet-evm = { workspace = true }
pallet-nonfungible = { workspace = true }
pallet-proxy-rmrk-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
up-data-structs = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ['frame-benchmarking', 'frame-support/runtime-benchmarks', 'frame-system/runtime-benchmarks']
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-common/std",
	"pallet-evm/std",
	"pallet-nonfungible/std",
	"pallet-proxy-rmrk-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"up-data-structs/std",
	'frame-benchmarking/std',
]
try-runtime = ["frame-support/try-runtime"]
