[package]
edition = "2021"
license = "GPLv3"
name = "pallet-test-utils"
publish = false
version = "0.1.0"

[dependencies]
# Note: `package = "parity-scale-codec"` must be supplied since the `Encode` macro searches for it.
codec = { workspace = true, package = "parity-scale-codec" }

frame-support = { workspace = true }
frame-system = { workspace = true }
scale-info = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-std/std",
]
try-runtime = ["frame-support/try-runtime", "pallet-unique-scheduler-v2/try-runtime"]
