[package]
name = "pallet-unq-scheduler"
version = "0.1.0"
authors = ["Unique Network <support@uniquenetwork.io>"]
edition = "2021"
license = "GPLv3"
homepage = "https://unique.network"
repository = "https://github.com/UniqueNetwork/unique-chain"
description = "Unique Scheduler pallet"
readme = "README.md"

[dependencies]
serde = { version = "1.0.130", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false }
scale-info = { version = "2.0.1", default-features = false, features = [
	"derive",
] }
frame-support = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
frame-system = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-runtime = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-std = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-io = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
frame-benchmarking = { default-features = false, optional = true, git = 'https://github.com/paritytech/substrate', branch = 'master' }

up-sponsorship = { version = "0.1.0", default-features = false, git = "https://github.com/uniquenetwork/pallet-sponsoring", branch = 'master' }
log = { version = "0.4.14", default-features = false }

[dev-dependencies]
sp-core = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
substrate-test-utils = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-runtime/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"up-sponsorship/std",
	"sp-io/std",
	"sp-std/std",
	"log/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
#try-runtime = ["frame-support/try-runtime"]
