[build-dependencies]
substrate-build-script-utils = '3.0.0'

[[bin]]
name = 'nft'

[package]
authors = ['UseTech Professional <https://usetech.com/blockchain>']
build = 'build.rs'
description = 'Substrate node nft'
edition = '2018'
homepage = 'https://usetech.com/blockchain'
license = 'All Rights Reserved'
name = 'nft'
repository = 'https://github.com/usetech-llc/nft_private/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures = '0.3.4'
log = '0.4.8'
flexi_logger = "0.15.7"
parking_lot = '0.10.0'
structopt = '0.3.8'
jsonrpc-core = '15.0.0'

# Substrate dependencies
nft-runtime = { path = '../runtime', version = '3.0.0' }
frame-benchmarking = '3.0.0'
frame-benchmarking-cli = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-basic-authorship = '0.9.0'
sc-cli = { features = ['wasmtime'], version = '0.9.0' }
sc-client-api = '3.0.0'
sc-consensus = '0.9.0'
sc-consensus-aura = '0.9.0'
sc-executor = { features = ['wasmtime'], version = '0.9.0' }
sc-finality-grandpa = '0.9.0'

sc-keystore = '3.0.0'
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = { features = ['wasmtime'], version = '0.9.0' }
sc-transaction-pool = '3.0.0'
sp-api = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-consensus = '0.9.0'
sp-consensus-aura = '0.9.0'
sp-core = '3.0.0'
sp-finality-grandpa = '3.0.0'
sp-inherents = '3.0.0'
sp-runtime = '3.0.0'
sp-transaction-pool = '3.0.0'
substrate-frame-rpc-system = '3.0.0'
sc-network = '0.9.0'
pallet-contracts-rpc = '3.0.0'
sc-telemetry = '3.0.0'

serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"

[features]
default = []
runtime-benchmarks = ['nft-runtime/runtime-benchmarks']
