[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[[bin]]
name = 'nft'

[package]
authors = ['UseTech Professional <https://usetech.com/blockchain>']
build = 'build.rs'
description = 'Substrate node nft'
edition = '2018'
homepage = 'https://usetech.com/blockchain'
license = 'Unlicense'
name = 'nft'
repository = 'https://github.com/substrate-developer-hub/nft/'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures = '0.3.4'
log = '0.4.8'
parking_lot = '0.10.0'
structopt = '0.3.8'
jsonrpc-core = '15.0.0'

[dependencies.nft-runtime]
path = '../runtime'
version = '2.0.0'

[dependencies.sc-basic-authorship]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-cli]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-client-api]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[dependencies.sc-consensus]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.pallet-contracts-rpc]
git = 'https://github.com/usetech-llc/substrate.git'
version = '0.8.0'
branch = 'v2.0.0_release'

[dependencies.sc-rpc]
git = 'https://github.com/usetech-llc/substrate.git'
version = '2.0.0'
branch = 'v2.0.0_release'

[dependencies.sp-api]
git = 'https://github.com/usetech-llc/substrate.git'
version = '2.0.0'
branch = 'v2.0.0_release'

[dependencies.sp-blockchain]
git = 'https://github.com/usetech-llc/substrate.git'
version = '2.0.0'
branch = 'v2.0.0_release'

[dependencies.sp-block-builder]
git = 'https://github.com/usetech-llc/substrate.git'
version = '2.0.0'
branch = 'v2.0.0_release'

[dependencies.sc-rpc-api]
git = 'https://github.com/usetech-llc/substrate.git'
version = '0.8.0'
branch = 'v2.0.0_release'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/usetech-llc/substrate.git'
version = '2.0.0'
branch = 'v2.0.0_release'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/usetech-llc/substrate.git'
version = '2.0.0'
branch = 'v2.0.0_release'

[dependencies.sc-consensus-aura]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-executor]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-network]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-service]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sc-transaction-pool]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[dependencies.sp-consensus]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sp-consensus-aura]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '0.8.0'

[dependencies.sp-core]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[dependencies.sp-finality-grandpa]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[dependencies.sp-inherents]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[dependencies.sp-runtime]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'

[dependencies.sp-transaction-pool]
git = 'https://github.com/usetech-llc/substrate.git'
branch = 'v2.0.0_release'
version = '2.0.0'
