[package]
name = "pallet-evm-transaction-payment"
version = "0.1.0"
license = "GPLv3"
edition = "2021"

[dependencies]
scale-info = { version = "2.0.1", default-features = false, features = [
    "derive",
] }
frame-support = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
frame-system = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-runtime = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-std = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-io = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-core = { default-features = false, git = 'https://github.com/paritytech/substrate', branch = 'master' }
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "master" }
fp-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "master" }
pallet-ethereum = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "master" }
up-sponsorship = { version = "0.1.0", default-features = false, git = "https://github.com/uniquenetwork/pallet-sponsoring", branch = 'master' }
fp-evm-mapping = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "master" }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.1.2'

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
    "sp-core/std",
    "pallet-evm/std",
    "pallet-ethereum/std",
    "fp-evm/std",
    "up-sponsorship/std",
    "fp-evm-mapping/std",
]
