[package]
authors = ['Unique Network <support@uniquenetwork.io>']
description = 'Unique Runtime Common Primitives'
edition = '2021'
homepage = 'https://unique.network'
license = 'All Rights Reserved'
name = 'up-common'
repository = 'https://github.com/UniqueNetwork/unique-chain'
version = "0.9.27"

[features]
default = ['std']
std = [
    'sp-std/std',
    'frame-support/std',
    'sp-runtime/std',
    'sp-core/std',
    'sp-consensus-aura/std',
    'fp-rpc/std',
    'pallet-evm/std',
]

[dependencies.sp-std]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.27"

[dependencies.frame-support]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.27"

[dependencies.sp-runtime]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.27"

[dependencies.sp-core]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.27"

[dependencies.sp-consensus-aura]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.27"

[dependencies.fp-rpc]
default-features = false
git = "https://github.com/uniquenetwork/frontier"
rev = "89a37c5a489f426cc7a42d7b94019974093a052d"

[dependencies.pallet-evm]
default-features = false
git = "https://github.com/uniquenetwork/frontier"
rev = "89a37c5a489f426cc7a42d7b94019974093a052d"
