[package]
edition = "2021"
license = "GPLv3"
name = "pallet-xfun"
version = "0.1.0"

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
pallet-common = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
staging-xcm = { workspace = true }
staging-xcm-executor = { workspace = true }
up-data-structs = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-common/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	"staging-xcm-executor/std",
	"up-data-structs/std",
]
try-runtime = ["frame-support/try-runtime"]
