[package]
edition = "2021"
license = ""
name = "rmrk-rpc"
version = "0.0.2"

[dependencies]
codec = { workspace = true }
rmrk-traits = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "rmrk-traits/std", "sp-api/std", "sp-runtime/std", "sp-std/std"]
