version: "3.5"

services:
  node-parachain:
    build:
      args:
        - "RUST_TOOLCHAIN=nightly-2022-07-24"
        - "BRANCH=release-v927020"
        - "REPO_URL=https://github.com/UniqueNetwork/unique-chain.git"
        - "FEATURE=quartz-runtime"
        - "RUNTIME=quartz"
        - "POLKADOT_BUILD_BRANCH=release-v0.9.27"
        - "MAINNET_TAG="
        - "MAINNET_BRANCH=quartz-v924012-2"
      context: ../
      dockerfile: .docker/Dockerfile-parachain-upgrade
    image: node-parachain
    container_name: node-parachain
    volumes:
       - type: bind
         source: ./launch-config-forkless-nodata.json
         target: /polkadot-launch/launch-config.json
         read_only: true
    expose:
      - 9944
      - 9933
    ports:
      - 127.0.0.1:9944:9944
      - 127.0.0.1:9933:9933
    logging:
      options:
        max-size: "1m"
        max-file: "3"
