version: "3.5"

services:
  node-dev:
    build:
      args:
        - "RUST_TOOLCHAIN=nightly-2022-07-24"
        - "FEATURE=opal-runtime"
      context: ../
      dockerfile: .docker/Dockerfile-chain-dev
    expose:
      - 9944
      - 9933
    ports:
      - 127.0.0.1:9944:9944
      - 127.0.0.1:9933:9933
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    command: cargo run --release --features=$FEATURE -- --dev -linfo --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external

