# Workflow which controls starts nested workflows.
name: develop

# Triger: PR at 'develop' branch with following types of events.
on:
  pull_request:
    branches: [ 'develop' ]
    types: [ opened, reopened, synchronize, ready_for_review, converted_to_draft ]

#Concurency group for control execution queue over github runners.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# List of a jobs included into Workflow.
jobs:

  yarn-test-dev:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/dev-build-tests_v2.yml


  unit-test:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/unit-test_v2.yml

  canary:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'canary')) }}
    uses: ./.github/workflows/canary.yml
    secrets: inherit # pass all secrets

  xcm:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'xcm')) }}
    uses: ./.github/workflows/xcm.yml
    secrets: inherit # pass all secrets
    
  forkless:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'forkless')) }}
    uses: ./.github/workflows/forkless.yml
  
  node-only-update:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'forkless')) }}
    uses: ./.github/workflows/node-only-update_v2.yml
    
  parallel_and_sequential_tests:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'para')) }}
    uses: ./.github/workflows/node-only-update_v3.yml

  codestyle:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/codestyle_v2.yml
  
  yarn_eslint:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/test_codestyle_v2.yml
