# https://cryptousetech.atlassian.net/wiki/spaces/CI/pages/2586869783/CI+Develop
# Workflow which controls starts nested workflows.
name: develop

# Triger: PR at 'develop' branch with following types of events.
on:
  pull_request:
    branches: [ 'develop', 'release-v930032' ]
    types: [ opened, reopened, synchronize, ready_for_review, converted_to_draft ]

#Concurency group for control execution queue over github runners.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# List of a jobs included into Workflow.
jobs:

  # yarn-test-dev:
  #   if: github.event.pull_request.draft == false                                                                             # Conditional check for draft per job.
  #   uses: ./.github/workflows/dev-build-tests_v2.yml


  # unit-test:
  #   if: github.event.pull_request.draft == false                                                                             # Conditional check for draft per job.
  #   uses: ./.github/workflows/unit-test_v2.yml

  canary:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'canary')) }}    # Conditional check for draft & labels per job.
    uses: ./.github/workflows/canary.yml
    secrets: inherit # pass all secrets from initial workflow to nested

  xcm:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'xcm')) }}       # Conditional check for draft & labels per job.
    uses: ./.github/workflows/xcm.yml
    secrets: inherit # pass all secrets from initial workflow to nested
    
  forkless:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'forkless')) }}  # Conditional check for draft & labels per job.
    uses: ./.github/workflows/forkless.yml
  
  node-only-update:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'node-only-update')) }}  # Conditional check for draft & labels per job.
    uses: ./.github/workflows/node-only-update_v2.yml
    
  parallel_and_sequential_tests:
    if: ${{ (github.event.pull_request.draft == false && contains( github.event.pull_request.labels.*.name, 'integration')) }}      # Conditional check for draft & labels per job.
    uses: ./.github/workflows/integration-tests.yml

  # codestyle:
  #   if: github.event.pull_request.draft == false                                                                             # Conditional check for draft per job.
  #   uses: ./.github/workflows/codestyle_v2.yml
  
  # yarn_eslint:
  #   if: github.event.pull_request.draft == false                                                                             # Conditional check for draft per job.
  #   uses: ./.github/workflows/test_codestyle_v2.yml
