name: develop

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize   #commit(s) pushed to the pull request
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  yarn-test-dev:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/reusable/dev-build-tests_v2.yml

  unit-test:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/reusable/unit-test_v2.yml

  forkless:
    if: contains( github.event.pull_request.labels.*.name, 'forkless') 
    uses: ./.github/workflows/reusable/forkless.yml

  canary:
    if: contains( github.event.pull_request.labels.*.name, 'canary')
    uses: ./.github/workflows/reusable/canary.yml
    secrets: inherit # pass all secrets


  xcm:
    if: contains( github.event.pull_request.labels.*.name, 'xcm')
    uses: ./.github/workflows/reusable/xcm.yml

  codestyle:
    uses: ./.github/workflows/reusable/codestyle_v2.yml