name: Code style

on: [push]

jobs:
  rustfmt:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Install substrate dependencies
        run: sudo apt-get install libssl-dev pkg-config libclang-dev clang
      - uses: icepuma/rust-action@master
        with:
          args: cargo clippy -- -Dwarnings