# https://cryptousetech.atlassian.net/wiki/spaces/CI/pages/2586837012/Code+style+testing
# Nested workflow for checks related to formatting Rust code 

name: make-bench

# Triger: only call from main workflow(re-usable workflows)
on:
  push:
    branches:
      - "feature/ci-make-bench"
  workflow_dispatch:

jobs:
  bench:
    runs-on: [ XL ]
    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      - uses: actions/checkout@v3.3.0
        with:
          ref: develop 

      - name: Read .env file
        uses: xom9ikk/dotenv@v2        

      - name: Install substrate dependencies
        run: sudo apt-get install libssl-dev pkg-config libclang-dev clang protobuf-compiler

      - name: Install actual toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ env.RUST_TOOLCHAIN }}
            default: true
            target: wasm32-unknown-unknown

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # - name: Create new branch from develop
      #   run: |
      #     git config user.name "Unique"
      #     git config user.email github-actions@usetech.com
      #     git checkout -b ci/make-bench develop

      - name: RUN benchmarking
        run: |
          time make bench-unique

      - name: show git diff
        run: |
          git diff

      # - name: Create PR
      #   run: |
      #     git config user.name "Unique"
      #     git config user.email github-actions@usetech.com
      #     git commit -a -m "commit benchmarking for on $(date)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          base: develop
          branch: ci/make-bench
          commit-message: commit benchmarking
          committer: Unique <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          title: 'CI Make BENCH'
          assignees: BuddyGlas
          reviewers: BuddyGlas
