name: Tests code style

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: self-hosted-ci

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install modules
      run: cd tests && yarn
    - name: Run ESLint
      run: cd tests && yarn eslint --ext .ts,.js src/
