name: Try Runtime

# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize   #commit(s) pushed to the pull request
      - ready_for_review

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#Define Workflow variables
env:
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  prepare-execution-marix-try-runtime:
    
    name: Prepare execution matrix for fork
    
    runs-on: self-hosted-ci
    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}
    steps:
      - name: Skip if pull request is in Draft
        # `if: github.event.pull_request.draft == true` should be kept here, at
        # the step level, rather than at the job level. The latter is not
        # recommended because when the PR is moved from "Draft" to "Ready to
        # review" the workflow will immediately be passing (since it was skipped),
        # even though it hasn't actually ran, since it takes a few seconds for
        # the workflow to start. This is also disclosed in:
        # https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/17
        # That scenario would open an opportunity for the check to be bypassed:
        # 1. Get your PR approved
        # 2. Move it to Draft
        # 3. Push whatever commits you want
        # 4. Move it to "Ready for review"; now the workflow is passing (it was
        #    skipped) and "Check reviews" is also passing (it won't be updated
        #    until the workflow is finished)
        if: github.event.pull_request.draft == true
        run: exit 1

      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  #Checking out head commit

      - name: Read .env file
        uses: xom9ikk/dotenv@v1.0.2

      - name: Create Execution matrix
        uses: fabiocaccamo/create-matrix-action@v2
        id: create_matrix
        with:
          matrix: |
            network {Opal}, features {opal-runtime}, fork_from_address {'wss://eu-ws-opal.unique.network:443'}
            network {Quartz}, features {quartz-runtime}, fork_from_address {'wss://eu-ws-quartz.unique.network:443'}
            network {Unique}, features {unique-runtime}, fork_from_address {'wss://eu-ws.unique.network:443'}



  fork-update-withdata:
    needs: prepare-execution-marix-try-runtime
    # The type of runner that the job will run on
    runs-on: self-hosted-ci

    name: Build Container, Spin it Up an test

    continue-on-error: true         #Do not stop testing of matrix runs failed.  As it decided during PR review - it required 50/50& Let's check it with false.

    strategy:
      matrix:
        include: ${{fromJson(needs.prepare-execution-marix-try-runtime.outputs.matrix)}}

    steps:

      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  #Checking out head commit

      - name: Read .env file
        uses: xom9ikk/dotenv@v1.0.2

      - name: Generate ENV related extend file for docker-compose
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .docker/forking/docker-compose.try-runtime.j2
          output_file: .docker/forking/docker-compose.${{ matrix.network }}.yml
          variables: |
            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git
            RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}
            POLKADOT_BUILD_BRANCH=${{ env.POLKADOT_BUILD_BRANCH }}
            FEATURE=${{ matrix.features }}
            BRANCH=${{ github.head_ref }}
            FORK_FROM=${{ matrix.fork_from_address }}

      - name: Show build configuration
        run: cat .docker/docker-compose.try-runtime.${{ matrix.network }}.yml


      - name: Build the stack
        run: docker-compose -f ".docker/docker-compose-try-runtime.yaml" -f ".docker/docker-compose.try-runtime.${{ matrix.network }}.yml" up -d --build  --force-recreate --timeout 300


      - name: Collect Docker Logs
        if: success() || failure()
        uses: jwalton/gh-docker-logs@v2.2.0
        with:
          dest: './try-runtime-logs.${{ matrix.features }}'
          images: 'try-runtime' 

      - name: Tar logs
        if: success() || failure()
        run: tar cvzf ./try-runtime-logs.${{ matrix.features }}.tgz ./try-runtime-logs.${{ matrix.features }}

      - name: Upload logs to GitHub
        if: success() || failure()
        uses: actions/upload-artifact@master
        with:
          name: try-runtime-logs.${{ matrix.features }}.tgz
          path: ./try-runtime-logs.${{ matrix.features }}.tgz

      - name: Stop running containers
        if: always()                   # run this step always
        run: docker-compose -f ".docker/forking/docker-compose-try-runtime.yaml" -f ".docker/forking/docker-compose.try-runtime.${{ matrix.network }}.yml" down
