name: Nesting XCM

on:
  workflow_call:


jobs:

  xcm-testnet-build:
    name: testnet build
    uses: ./.github/workflows/xcm-testnet-build.yml
    secrets: inherit

  xcm-build-results:
    run: echo ${{needs.xcm-testnet-build.result}}

  xcm-tests:
    name: tests
    needs: [ xcm-testnet-build ]
    uses: ./.github/workflows/xcm-tests_v2.yml


