name: Nesting XCM

on:
  workflow_call:


jobs:

  xcm-testnet-build:
    name: testnet build
    uses: ./.github/workflows/reusable/xcm-testnet-build.yml
    secrets: inherit

  xcm-tests:
    name: tests
    needs: [ xcm-testnet-build ]
    uses: ./.github/workflows/reusable/xcm-tests_v2.yml


