[package]
edition = "2021"
name = "pallet-structure"
version = "0.1.2"

[dependencies]
# Note: `package = "parity-scale-codec"` must be supplied since the `Encode` macro searches for it.
codec = { workspace = true, package = "parity-scale-codec" }

scale-info = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
pallet-common = { workspace = true }
pallet-evm = { workspace = true }
sp-std = { workspace = true }
up-data-structs = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ['frame-benchmarking', 'pallet-common/runtime-benchmarks']
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-common/std",
	"pallet-evm/std",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"up-data-structs/std",
]
try-runtime = ["frame-support/try-runtime"]
